POST http://localhost:3000/games
Content-type: application/json

{
    "nivel": "1"
}

###
GET http://localhost:3000/games

###
GET http://localhost:3000/games/19

###
PATCH  http://localhost:3000/games/f6977461-cd40-406d-a71c-196cfc285836
Content-type: application/json

{
    "nivel": "1"

}

###
DELETE http://localhost:3000/games/5