POST http://localhost:3000/games
Content-type: application/json

{
    "nivel": "1"
}

###
GET http://localhost:3000/games

###
GET http://localhost:3000/games/19

###
PATCH  http://localhost:3000/games/d1d36dd0-0cf6-4c5e-a027-331c7995c41c
Content-type: application/json

{
    "nivel": "1"

}

###
DELETE http://localhost:3000/games/5